/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CommownSWV2Interface extends ethers.utils.Interface {
  functions: {
    "VERSION()": FunctionFragment;
    "balancePerUser(address)": FunctionFragment;
    "confirmationNeeded()": FunctionFragment;
    "getPocketFull(uint256)": FunctionFragment;
    "getPocketLight(uint256)": FunctionFragment;
    "initialize(address[],uint8,address)": FunctionFragment;
    "isOwner(address)": FunctionFragment;
    "isSigned(uint256,address)": FunctionFragment;
    "numConfirmations(uint256)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "owners(uint256)": FunctionFragment;
    "pocketMaxID()": FunctionFragment;
    "pockets(uint256)": FunctionFragment;
    "proposePocket(address,bytes,uint256,tuple[],address,uint256,uint256,uint8)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "sharePerUser(uint256,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "voteForPocket(uint256)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balancePerUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmationNeeded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPocketFull",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPocketLight",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string[], BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isSigned",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "numConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pocketMaxID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pockets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposePocket",
    values: [
      string,
      BytesLike,
      BigNumberish,
      { user: string; share: BigNumberish }[],
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharePerUser",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteForPocket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balancePerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmationNeeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPocketFull",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPocketLight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSigned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pocketMaxID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pockets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposePocket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharePerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteForPocket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Deposit(address,uint256,uint256,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ProposePocket(address,uint256,address,bytes,uint8,uint8,uint256,tuple[])": EventFragment;
    "Upgraded(address)": EventFragment;
    "VotePocket(address,uint256,uint8)": EventFragment;
    "WalletCreated(address,address[],uint256)": EventFragment;
    "Withdraw(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposePocket"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VotePocket"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WalletCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export type AdminChangedEvent = TypedEvent<
  [string, string] & { previousAdmin: string; newAdmin: string }
>;

export type BeaconUpgradedEvent = TypedEvent<[string] & { beacon: string }>;

export type DepositEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber] & {
    sender: string;
    amount: BigNumber;
    userBalance: BigNumber;
    balance: BigNumber;
  }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ProposePocketEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    number,
    number,
    BigNumber,
    ([string, BigNumber] & { user: string; share: BigNumber })[]
  ] & {
    sender: string;
    pocketID: BigNumber;
    to: string;
    data: string;
    pStatus: number;
    pType: number;
    totalAmount: BigNumber;
    sharePerUser: ([string, BigNumber] & { user: string; share: BigNumber })[];
  }
>;

export type UpgradedEvent = TypedEvent<[string] & { implementation: string }>;

export type VotePocketEvent = TypedEvent<
  [string, BigNumber, number] & {
    sender: string;
    pocketID: BigNumber;
    numConfirmation: number;
  }
>;

export type WalletCreatedEvent = TypedEvent<
  [string, string[], BigNumber] & {
    creator: string;
    owners: string[];
    confirmationNeeded: BigNumber;
  }
>;

export type WithdrawEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber] & {
    sender: string;
    amount: BigNumber;
    userBalance: BigNumber;
    balance: BigNumber;
  }
>;

export class CommownSWV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CommownSWV2Interface;

  functions: {
    VERSION(overrides?: CallOverrides): Promise<[string]>;

    balancePerUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    confirmationNeeded(overrides?: CallOverrides): Promise<[number]>;

    getPocketFull(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        number,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        to: string;
        item: string;
        data: string;
        pStatus: number;
        pType: number;
        totalAmount: BigNumber;
        id: BigNumber;
        qty: BigNumber;
      }
    >;

    getPocketLight(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, BigNumber, BigNumber, BigNumber] & {
        item: string;
        pStatus: number;
        pType: number;
        totalAmount: BigNumber;
        id: BigNumber;
        qty: BigNumber;
      }
    >;

    initialize(
      _owners: string[],
      _confirmationNeeded: BigNumberish,
      _admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isSigned(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    numConfirmations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    pocketMaxID(overrides?: CallOverrides): Promise<[BigNumber]>;

    pockets(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    proposePocket(
      _to: string,
      _data: BytesLike,
      _totalAmount: BigNumberish,
      _shares: { user: string; share: BigNumberish }[],
      _tokenAdrs: string,
      _tokenId: BigNumberish,
      _tokenQty: BigNumberish,
      pType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sharePerUser(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voteForPocket(
      _pocketID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  VERSION(overrides?: CallOverrides): Promise<string>;

  balancePerUser(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  confirmationNeeded(overrides?: CallOverrides): Promise<number>;

  getPocketFull(
    _pocketID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      number,
      number,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      to: string;
      item: string;
      data: string;
      pStatus: number;
      pType: number;
      totalAmount: BigNumber;
      id: BigNumber;
      qty: BigNumber;
    }
  >;

  getPocketLight(
    _pocketID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, number, number, BigNumber, BigNumber, BigNumber] & {
      item: string;
      pStatus: number;
      pType: number;
      totalAmount: BigNumber;
      id: BigNumber;
      qty: BigNumber;
    }
  >;

  initialize(
    _owners: string[],
    _confirmationNeeded: BigNumberish,
    _admin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isSigned(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  numConfirmations(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  onERC721Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  pocketMaxID(overrides?: CallOverrides): Promise<BigNumber>;

  pockets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  proposePocket(
    _to: string,
    _data: BytesLike,
    _totalAmount: BigNumberish,
    _shares: { user: string; share: BigNumberish }[],
    _tokenAdrs: string,
    _tokenId: BigNumberish,
    _tokenQty: BigNumberish,
    pType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sharePerUser(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voteForPocket(
    _pocketID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    VERSION(overrides?: CallOverrides): Promise<string>;

    balancePerUser(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    confirmationNeeded(overrides?: CallOverrides): Promise<number>;

    getPocketFull(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        number,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        to: string;
        item: string;
        data: string;
        pStatus: number;
        pType: number;
        totalAmount: BigNumber;
        id: BigNumber;
        qty: BigNumber;
      }
    >;

    getPocketLight(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, BigNumber, BigNumber, BigNumber] & {
        item: string;
        pStatus: number;
        pType: number;
        totalAmount: BigNumber;
        id: BigNumber;
        qty: BigNumber;
      }
    >;

    initialize(
      _owners: string[],
      _confirmationNeeded: BigNumberish,
      _admin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isSigned(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    numConfirmations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    pocketMaxID(overrides?: CallOverrides): Promise<BigNumber>;

    pockets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    proposePocket(
      _to: string,
      _data: BytesLike,
      _totalAmount: BigNumberish,
      _shares: { user: string; share: BigNumberish }[],
      _tokenAdrs: string,
      _tokenId: BigNumberish,
      _tokenQty: BigNumberish,
      pType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    sharePerUser(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    voteForPocket(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    BeaconUpgraded(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    "Deposit(address,uint256,uint256,uint256)"(
      sender?: string | null,
      amount?: null,
      userBalance?: null,
      balance?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        sender: string;
        amount: BigNumber;
        userBalance: BigNumber;
        balance: BigNumber;
      }
    >;

    Deposit(
      sender?: string | null,
      amount?: null,
      userBalance?: null,
      balance?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        sender: string;
        amount: BigNumber;
        userBalance: BigNumber;
        balance: BigNumber;
      }
    >;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "ProposePocket(address,uint256,address,bytes,uint8,uint8,uint256,tuple[])"(
      sender?: string | null,
      pocketID?: null,
      to?: null,
      data?: null,
      pStatus?: null,
      pType?: null,
      totalAmount?: null,
      sharePerUser?: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        string,
        string,
        number,
        number,
        BigNumber,
        ([string, BigNumber] & { user: string; share: BigNumber })[]
      ],
      {
        sender: string;
        pocketID: BigNumber;
        to: string;
        data: string;
        pStatus: number;
        pType: number;
        totalAmount: BigNumber;
        sharePerUser: ([string, BigNumber] & {
          user: string;
          share: BigNumber;
        })[];
      }
    >;

    ProposePocket(
      sender?: string | null,
      pocketID?: null,
      to?: null,
      data?: null,
      pStatus?: null,
      pType?: null,
      totalAmount?: null,
      sharePerUser?: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        string,
        string,
        number,
        number,
        BigNumber,
        ([string, BigNumber] & { user: string; share: BigNumber })[]
      ],
      {
        sender: string;
        pocketID: BigNumber;
        to: string;
        data: string;
        pStatus: number;
        pType: number;
        totalAmount: BigNumber;
        sharePerUser: ([string, BigNumber] & {
          user: string;
          share: BigNumber;
        })[];
      }
    >;

    "Upgraded(address)"(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;

    Upgraded(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;

    "VotePocket(address,uint256,uint8)"(
      sender?: string | null,
      pocketID?: null,
      numConfirmation?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      { sender: string; pocketID: BigNumber; numConfirmation: number }
    >;

    VotePocket(
      sender?: string | null,
      pocketID?: null,
      numConfirmation?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      { sender: string; pocketID: BigNumber; numConfirmation: number }
    >;

    "WalletCreated(address,address[],uint256)"(
      creator?: string | null,
      owners?: null,
      confirmationNeeded?: null
    ): TypedEventFilter<
      [string, string[], BigNumber],
      { creator: string; owners: string[]; confirmationNeeded: BigNumber }
    >;

    WalletCreated(
      creator?: string | null,
      owners?: null,
      confirmationNeeded?: null
    ): TypedEventFilter<
      [string, string[], BigNumber],
      { creator: string; owners: string[]; confirmationNeeded: BigNumber }
    >;

    "Withdraw(address,uint256,uint256,uint256)"(
      sender?: string | null,
      amount?: null,
      userBalance?: null,
      balance?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        sender: string;
        amount: BigNumber;
        userBalance: BigNumber;
        balance: BigNumber;
      }
    >;

    Withdraw(
      sender?: string | null,
      amount?: null,
      userBalance?: null,
      balance?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        sender: string;
        amount: BigNumber;
        userBalance: BigNumber;
        balance: BigNumber;
      }
    >;
  };

  estimateGas: {
    VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    balancePerUser(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    confirmationNeeded(overrides?: CallOverrides): Promise<BigNumber>;

    getPocketFull(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPocketLight(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _owners: string[],
      _confirmationNeeded: BigNumberish,
      _admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isSigned(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numConfirmations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    pocketMaxID(overrides?: CallOverrides): Promise<BigNumber>;

    pockets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    proposePocket(
      _to: string,
      _data: BytesLike,
      _totalAmount: BigNumberish,
      _shares: { user: string; share: BigNumberish }[],
      _tokenAdrs: string,
      _tokenId: BigNumberish,
      _tokenQty: BigNumberish,
      pType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sharePerUser(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voteForPocket(
      _pocketID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balancePerUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    confirmationNeeded(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPocketFull(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPocketLight(
      _pocketID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _owners: string[],
      _confirmationNeeded: BigNumberish,
      _admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isOwner(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSigned(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numConfirmations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owners(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pocketMaxID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pockets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposePocket(
      _to: string,
      _data: BytesLike,
      _totalAmount: BigNumberish,
      _shares: { user: string; share: BigNumberish }[],
      _tokenAdrs: string,
      _tokenId: BigNumberish,
      _tokenQty: BigNumberish,
      pType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sharePerUser(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voteForPocket(
      _pocketID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
